export const r = {
    type_map: 0,
    type_array: 1,
    type_choice: 2,
    type_optional: 3,
    parse_varint: 4,
    parse_bit_size: 5,
    parse_text: 6,
    parse_type_data_immediate: 7,

    type_array_bit: 8,
    type_array_fixed: 9,
    type_array_chunk: 10,
    type_choice_shared: 11,
    type_choice_select: 12,
    parse_align: 13,
    parse_type_data: 14,
    parse_bytes: 15,
    little_endian_marker: 16,

    nonexistent: 17,
    describe_no_value: 18,
    false: 19,
    true: 20,
    value: 21,
    integer_signed: 22,
    IEEE_754_binary16: 23,
    IEEE_754_binary32: 24,
    IEEE_754_binary64: 25,
    exponent_base2: 26,
    exponent_base10: 27,
    text: 28,
    bytes: 29,
    epoch_seconds_continuous: 30,
    registry: 31,
    error: 32,
    copyable: 33,
    copy_length: 34,
    copy_distance: 35,
    flatten_array: 36,
    delta: 37,
    delta_double: 38,
    offset_add: 39,
    unit: 40,
    format: 41,
    prefix: 42,
    suffix: 43,
    prefix_delta: 44,
    operation: 45,
    reference: 46,
    credential: 47,

    error_internal: 64,
    incomplete_stream: 65,
    registry_symbol_not_accepted: 66,
    registry_symbol_not_accepted_as_array_type: 67,
    stream_position: 68,

    sign: 69,
    denominator: 70,
    complex_i: 71,
    quaternion_j: 72,
    quaternion_k: 73,

    instant: 74,
    implied_interval: 75,
    duration: 76,
    start: 77,
    end: 78,

    year: 79,
    month: 80,
    day: 81,
    hour: 82,
    minute: 83,
    second: 84,

    data_type_not_accepted: 85,
    data_value_not_accepted: 86,
    data_path: 87,
    required_field_missing: 88,
    field_not_accepted: 89,
    field_order_not_accepted: 90,
    preamble_max_size_exceeded: 91,
    body_max_size_exceeded: 92,

    signature: 200,
    algorithm: 201,
    public_key: 202,
    ed25519: 203,

    magic_number: 8159,
} as const