export const enum r {
    type_map,
    type_array,
    type_choice,
    type_optional,
    parse_varint,
    parse_bit_size,
    parse_text,
    parse_type_data_immediate,

    type_array_bit,
    type_array_fixed,
    type_array_chunk,
    type_choice_shared,
    type_choice_select,
    parse_align,
    parse_type_data,
    parse_bytes,
    little_endian_marker,

    nonexistent,
    error = 32,
    error_internal = 64,
    incomplete_stream = 65,
    registry_symbol_not_accepted = 66,
    registry_symbol_not_accepted_as_array_type = 67,
    denominator = 70,
    magic_number = 8159,
}