export const enum r {
    type_map,
    type_array,
    type_choice,
    type_optional,
    parse_varint,
    parse_bit_size,
    parse_text,
    parse_type_data_immediate,

    type_array_bit,
    type_array_fixed,
    type_array_chunk,
    type_choice_shared,
    type_choice_select,
    parse_align,
    parse_type_data,
    parse_bytes,
    little_endian_marker,

    nonexistent = 26,
    error = 91,
    error_internal = 95,
    incomplete_stream = 96,
    denominator = 98,
    magic_number = 8159,
}