export const enum r {
    type_map,
    type_array,
    type_choice,
    type_optional,
    parse_varint,
    parse_bit_size,
    parse_text,
    parse_type_data_immediate,

    type_array_bit,
    type_array_fixed,
    type_array_chunk,
    type_choice_shared,
    type_choice_select,
    parse_align,
    parse_type_data,
    parse_bytes,
    little_endian_marker,

    nonexistent,
    describe_no_value,
    false,
    true,
    value = 21,
    error = 32,
    operation = 45,
    reference = 46,
    error_internal = 64,
    incomplete_stream,
    registry_symbol_not_accepted,
    registry_symbol_not_accepted_as_array_type,
    stream_position,
    denominator = 70,

    data_type_not_accepted = 85,
    data_value_not_accepted,
    data_path,
    required_field_missing,
    field_not_accepted,
    field_order_not_accepted,
    preamble_max_size_exceeded,
    body_max_size_exceeded,

    credential_token,
}